# Generated by Django 3.0.6 on 2020-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_blogs_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
