# Generated by Django 3.0.6 on 2020-12-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
