# Generated by Django 3.0.6 on 2020-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_auto_20201210_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='D:\\Project_\\My_Projects\\My_Portfolio\\portfolio_app\\static\\images\\inventory.png', upload_to='images'),
        ),
    ]
