# Generated by Django 3.0.6 on 2020-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20201210_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='D:/Project_/My_Projects/My_Portfolio/portfolio_app/tatic/images/inventory.png', upload_to='images'),
        ),
    ]
