# Generated by Django 3.0.6 on 2020-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_auto_20201210_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(default='static/images/inventory.png', upload_to='images'),
        ),
    ]
