# Generated by Django 3.0.6 on 2020-12-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_auto_20201210_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
